# Generated by Django 2.2 on 2020-01-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_commerce',
            name='picture',
            field=models.ImageField(default=True, max_length=200, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
