# Generated by Django 2.2 on 2020-01-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_e_commerce_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_commerce',
            name='picture',
            field=models.ImageField(max_length=1000, upload_to='pictures'),
        ),
    ]
