# Generated by Django 2.2 on 2020-01-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password1',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
