# Generated by Django 2.2 on 2020-01-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_register_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_commerce',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
