# Generated by Django 2.2 on 2020-01-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_auto_20200107_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_commerce',
            name='picture',
            field=models.ImageField(blank=True, max_length=1000, upload_to='pictures'),
        ),
    ]
