# Generated by Django 2.2 on 2020-01-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0009_auto_20200107_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_commerce',
            name='picture',
        ),
    ]
