# Generated by Django 2.2 on 2020-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_remove_e_commerce_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_commerce',
            name='picture',
            field=models.ImageField(blank=True, max_length=1000, upload_to='pictures'),
        ),
    ]
